"""Настройки параметров.
"""
from enum import IntEnum


class Limits(IntEnum):

    MAX_LEN_NAME_RECIPES = 200

    MAX_LEN_TEXT_RECIPES = 5000

    MAX_LEN_NAME_INGREDIENT = 128

    MAX_LEN_MEASUREMENT_INGREDIENT = 64

    MAX_LEN_NAME_TAG = 32

    MAX_LEN_SLUG_TAG = 32

    MAX_LEN_EMAIL_USER = 256

    MAX_LEN_USERNAME_USER = 32

    MAX_LEN_FIRST_NAME_USER = 32

    MAX_LEN_LAST_NAME_USER = 32

    MAX_LEN_PASSWORD_USER = 128
    MIN_COOKING_TIME = 1

    MAX_COOKING_TIME = 1440

    MIN_AMOUNT_SUM = 1

    MAX_AMOUNT_SUM = 1000

    PAGE_SIZE = 6
