volumes:
  pg:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - pg:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: blathata/foodgram_backend
    restart: always
    volumes:
      - static:/backend_static/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    image: blathata/foodgram_frontend
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
    env_file:
      - .env

  gateway:
    image: blatahata/foodgram_gateway
    restart: always
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media/
    env_file:
      - .env
    depends_on:
      - frontend
      - backend
      - db
