version: '2.6'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    container_name: foodgram-backend
    #image: blathata/foodgram_beckend:latest
    build: ../backend
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram-frontend
    #image: blathata/foodgram_frontend:latest
    build: ../frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
      # - 8001:80
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  static_value:
  media_value:
  postgres_data:
