# Generated by Django 5.1.4 on 2024-12-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(help_text='Обязательно для заполнения. Максимум 256 символов.', max_length=256, unique=True, verbose_name='Электроная почта пользователя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 символов.', max_length=32, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 символов.', max_length=32, verbose_name='Фамилия пользователя'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 128 символов.', max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(help_text='Обязательно для заполнения. Максимум 32 символов.', max_length=32, unique=True, verbose_name='Юзернейм'),
        ),
    ]
