# Generated by Django 5.1.5 on 2025-01-16 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(db_index=True, help_text='Обязательно для заполнения. Максимум 32 символов.', max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='Используйте только буквы и символы: w . @ + - ', regex='^[\\w.@+-]+$')], verbose_name='Юзернейм'),
        ),
    ]
